# Generated by Django 3.2.7 on 2021-12-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('company_name', models.CharField(max_length=100, verbose_name='Компания')),
                ('position_name', models.CharField(max_length=100, verbose_name='Должность')),
                ('hire_date', models.DateField(verbose_name='Дата приёма')),
                ('fire_date', models.DateField(null=True, verbose_name='Дата увольнения')),
                ('salary', models.PositiveIntegerField(verbose_name='Ставка, руб')),
                ('fraction', models.PositiveSmallIntegerField(verbose_name='Ставка, %')),
                ('base', models.PositiveIntegerField(verbose_name='База, руб')),
                ('advance', models.PositiveIntegerField(verbose_name='Аванс, руб')),
                ('by_hours', models.BooleanField(verbose_name='Почасовая оплата')),
            ],
        ),
    ]
